#!/usr/bin/env python3
"""Generate the frozen net geometry (after Gego's Reticulárea).

Run once, commit the output, never at build time:

    python3 scripts/generate-net.py

Writes src/assets/net/geometry.ts. Standard library only.
The rail has its own shape.
Python's `random` is reproducible for a given seed, so these seeds reproduce the
net approved in mockups/round-2/d-vanguardia.html exactly. Changing a seed
changes the mark: do it on purpose or not at all.
"""
import json, pathlib, random

ROOT = pathlib.Path(__file__).resolve().parent.parent

# name: (width, height, cols, rows, seed, node radius, progress axis, lit nodes, padding)
NETS = {
    'mark': (48, 36, 4, 3, 7, 1.7, 'x', [9], 3),
    'hero': (600, 400, 8, 5, 20, 3.5, 'x', [27], None),
    'rail': (150, 780, 3, 14, 41, 3.5, 'y', [], None),
}


def net(w, h, cols, rows, seed, r, axis, lit, pad):
    rnd = random.Random(seed)
    pad = pad if pad is not None else r * 2
    cw, rh = (w - 2 * pad) / (cols - 1), (h - 2 * pad) / (rows - 1)
    pts = {}
    for j in range(rows):
        for i in range(cols):
            x = pad + i * cw + (cw * .5 if j % 2 and i < cols - 1 else 0)
            y = pad + j * rh
            x += rnd.uniform(-.38, .38) * cw
            y += rnd.uniform(-.34, .34) * rh
            pts[(i, j)] = (min(w - pad, max(pad, x)), min(h - pad, max(pad, y)))
    edges = set()

    def add(a, b):
        if a in pts and b in pts:
            edges.add(tuple(sorted((a, b))))

    for (i, j) in pts:
        add((i, j), (i + 1, j))
        add((i, j), (i, j + 1))
        d = (i + 1, j + 1) if j % 2 else (i - 1, j + 1)
        add((i, j), d)
        if rnd.random() < .12:
            add((i, j), (i + 1, j + 1) if d[0] < i else (i - 1, j + 1))
    # drop some wires, keeping every node on at least two
    deg = {p: 0 for p in pts}
    for a, b in edges:
        deg[a] += 1
        deg[b] += 1
    for e in sorted(edges):
        a, b = e
        if rnd.random() < .16 and deg[a] > 2 and deg[b] > 2:
            edges.discard(e)
            deg[a] -= 1
            deg[b] -= 1
    k = 0 if axis == 'x' else 1
    ordered = sorted(pts, key=lambda p: pts[p][k])
    index = {p: n for n, p in enumerate(ordered)}
    rd = lambda v: round(v, 1)
    return {
        'w': w, 'h': h, 'r': r,
        # nodes in reading order along the axis: index = order in which they light
        'nodes': [[rd(pts[p][0]), rd(pts[p][1])] for p in ordered],
        'edges': sorted([sorted([index[a], index[b]]) for a, b in edges]),
        'lit': lit,
    }


def main():
    data = {name: net(*spec) for name, spec in NETS.items()}
    out = ROOT / 'src/assets/net/geometry.ts'
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        '// Generated by scripts/generate-net.py. Do not edit by hand.\n'
        'export interface NetGeometry { readonly w: number; readonly h: number; readonly r: number; readonly nodes: readonly (readonly [number, number])[]; readonly edges: readonly (readonly [number, number])[]; readonly lit: readonly number[]; }\n'
        f'export const nets = {json.dumps(data, separators=(",", ":"))} as const satisfies Record<string, NetGeometry>;\n'
        'export type NetName = keyof typeof nets;\n')
    for name, g in data.items():
        print(f'{name}: {len(g["nodes"])} nodes, {len(g["edges"])} wires')


if __name__ == '__main__':
    main()
